#cloud-config
# Create a group
groups:
  - hashicorp

write_files:
  - content: |
      server: https://${server_ip}:9345
      token: ${token}
    path: /etc/rancher/rke2/config.yaml

# Create users, in addition to the users provided by default
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - "ssh-rsa ${ssh_key}" # an SSH public key that is authorized
                      # to connect to this account
# Run a few commands (update apt's repo indexes and install curl)
runcmd:
  - sudo apt-get update
  - sudo apt install curl apt-transport-https iptables -q -y
  - export INSTALL_RKE2_TYPE="agent"
  - curl -sfL https://get.rke2.io | sudo sh -
  - sudo systemctl enable rke2-agent.service
  - sudo systemctl start rke2-agent.service
  - sudo systemctl status rke2-agent.service

